version: '3.9'
services:
  app:
    container_name: react-app-container
    image: node:16-alpine
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "yarn install && yarn start"
    ports:
      - '8000:3000'
